apiVersion: v1
kind: Service
metadata:
  name: vote
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000
  selector:
    role: vote
  type: LoadBalancer 
